### PR TITLE
Helper script enables starting playback from server webpage on another device

### PR DESCRIPTION
**Pull request by desean1625**
It allows me to start playback on RPi 2 from my ipad.

### CODE REVIEW

**Comment by hippojay** [comment]
Thanks. Let me check it out and I'll see about merging. The helper has been a bit neglected and since it was rewritten I haven't had a chance to re-learn what it does.   This is a good reason to have a look.

**Comment by wickning1** [comment]
I've been pre-occupied and helper seemed fairly stable so I've let it lie for a while. I'm here to answer questions though and planning to poke at that audio playing bug soon.

**Comment by wickning1** [comment]
I believe all the issues solved in these commits have been resolved in my version 3.4.7.  We should be able to close this pull request.

**Comment by desean1625** [comment]
I will check it out when I get a chance.

**Comment by desean1625** [comment]
Looks good.

**Comment by desean1625** [comment]
Thanks!

**Pull request closed without merging**
